export const PRODUCT_CATEGORIES = [
  "Tops",
  "Bottoms",
  "Outerwear",
  "Dresses",
  "Activewear",
  "Sleepwear",
  "Undergarments",
  "Footwear",
  "Accessories",
  "Swimwear",
  "Intimates",
  "Formalwear",
  "Maternity Wear",
  "Costumes",
  "Traditional Wear",
  "Loungewear",
  "Workwear",
];
